import { NextRequest, NextResponse } from 'next/server'
import { prisma } from '@/lib/db'
import { verifyAccessToken } from '@/lib/auth'
import { VideoProcessor } from '@/lib/video-processing'
import { processVideo } from '@/lib/video-processor'
import { uploadVideo } from '@/lib/s3'